# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy
env:
  AWS_DEFAULT_REGION: "ap-southeast-2"
on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: git clone the repo
      uses: actions/checkout@v2
      
    - name: prep nodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12'
   
    - name: build frontend
      run : cd home-security-frontend && npm install
  
    - name: build ses-mail-parser
      run : cd ses-mail-parser && npm install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     :  ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key :  ${{ secrets.AWS_SECRET_KEY }}
        aws-region            :  ${{ env.AWS_DEFAULT_REGION }}  
        
    - name: Deploy Frontend
    - run : npm install claudia -g
    - run : cd home-security-frontend && claudia update
